apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/plenary-student-428219-u9/locations/us-central1/clusters/dev-cluster

